[tox]
requires = tox>=4
envlist =
    # Django pre-release
    # py314-djpre,

    # Django 6.0
    {py312,py313,py314}-dj60,

    # Django 5.2
    {py310,py311,py312,py313,py314}-dj52,

[virtualenv]
discovery = pyenv

[testenv]
deps =
    pytest
    pytest-django
    testfixtures
    dj52: Django>=5.2,<5.3
    dj60: Django>=6.0,<6.3
    djpre: Django
pip_pre =
    djpre: true
setenv =
    PYTHONPATH = {toxinidir}
changedir = tests
commands = pytest {posargs}
